version: '3'

services:
  namenode:
    build: ./docker/hadoop
    container_name: hdfs-namenode
    hostname: namenode
    ports:
      - "9000:9000"  # HDFS
      - "9870:9870"  # WebUI
    environment:
      - CLUSTER_NAME=hadoop-cluster
    volumes:
      - hdfs-namenode-data:/hadoop/dfs/name
    networks:
      - hadoop-network

  datanode:
    build: ./docker/hadoop
    container_name: hdfs-datanode
    hostname: datanode
    depends_on:
      - namenode
    ports:
      - "9864:9864"  # Datanode WebUI
    environment:
      - SERVICE_PRECONDITION=namenode:9000
    volumes:
      - hdfs-datanode-data:/hadoop/dfs/data
    command: ["sh", "-c", "service ssh start && /opt/hadoop/bin/hdfs datanode"]
    networks:
      - hadoop-network

networks:
  hadoop-network:

volumes:
  hdfs-namenode-data:
  hdfs-datanode-data: