# === Spark Config ===
spark.master=local
spark.driver.memory=64M
spark.testing.memory=471859200

# === Input / Output ===
app.input.path=classpath:test_file.json
app.output.path=src/main/output
app.input.format=json
app.output.format=json
app.input.delimiter=;
app.output.delimiter=;
app.input.header=true
app.output.header=true

# === Transformation ===
app.transformation=sort
