apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs-namenode-pvc
  namespace: hadoop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs-datanode-pvc
  namespace: hadoop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi