apiVersion: v1
kind: Pod
metadata:
  name: hdfs-client
  namespace: hadoop
spec:
  containers:
    - name: hdfs-client
      image: bde2020/hadoop-base:2.0.0-hadoop3.2.1-java8
      command: ["sh", "-c", "sleep 3600"]