apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-simple
  namespace: hadoop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-simple
  template:
    metadata:
      labels:
        app: hdfs-simple
    spec:
      containers:
        - name: hdfs
          image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
          ports:
            - containerPort: 9000
            - containerPort: 9870
          env:
            - name: CLUSTER_NAME
              value: "hadoop-cluster"
            - name: CORE_CONF_fs_defaultFS
              value: "hdfs://hdfs-simple:9000"
---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-simple
  namespace: hadoop
spec:
  selector:
    app: hdfs-simple
  ports:
    - name: hdfs
      port: 9000
      targetPort: 9000
    - name: web
      port: 9870
      targetPort: 9870
  type: ClusterIP