name: Maven Package with HDFS Test

on:
  push:
    branches:
      - 'dev'

  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github

      - name: Create docker-compose.yml file
        run: |
          cat > docker-compose.yml << 'EOL'
          version: '3'

          services:
            namenode:
              image: apache/hadoop:3.3.4
              container_name: hdfs-namenode
              hostname: namenode
              ports:
                - "9000:9000"  # HDFS
                - "9870:9870"  # WebUI
              environment:
                - CLUSTER_NAME=hadoop-cluster
              volumes:
                - hdfs-namenode-data:/hadoop/dfs/name
              command: ["sh", "-c", "mkdir -p /hadoop/dfs/name && /opt/hadoop/bin/hdfs namenode -format && /opt/hadoop/bin/hdfs --daemon start namenode && tail -f /dev/null"]

            datanode:
              image: apache/hadoop:3.3.4
              container_name: hdfs-datanode
              hostname: datanode
              depends_on:
                - namenode
              ports:
                - "9864:9864"  # Datanode WebUI
              environment:
                - SERVICE_PRECONDITION=namenode:9000
              volumes:
                - hdfs-datanode-data:/hadoop/dfs/data
              command: ["sh", "-c", "mkdir -p /hadoop/dfs/data && /opt/hadoop/bin/hdfs --daemon start datanode && tail -f /dev/null"]

          volumes:
            hdfs-namenode-data:
            hdfs-datanode-data:
          EOL
          
          cat docker-compose.yml

      - name: Start HDFS with Docker Compose V2
        run: docker compose up -d

      - name: Wait for HDFS to be ready
        run: sleep 60

      - name: Verify HDFS containers
        run: docker ps

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Create test directory in HDFS
        run: |
          docker exec hdfs-namenode /opt/hadoop/bin/hdfs dfs -mkdir -p /test || true
        continue-on-error: true

      - name: Copy test files to HDFS
        run: |
          docker cp src/main/resources/test_file.csv hdfs-namenode:/tmp/ || true
          docker exec hdfs-namenode /opt/hadoop/bin/hdfs dfs -put /tmp/test_file.csv /test/ || true
        continue-on-error: true

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}